name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Runs every midnight
  workflow_dispatch:     # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # This action pulls your latest GitHub activity (commits, PRs, etc.)
      - name: Update GitHub Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Refreshed Profile Activity"
          MAX_LINES: 5
